repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --config=pyproject.toml ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
    - id: mypy